services:
  reverse-proxy:
    image: nginx:1.27-alpine3.20
    ports:
      - "80:80"
    networks:
      - library-network
    volumes:
      - ./Reverse-Proxy/nginx.conf:/etc/nginx/nginx.conf
  front:
    build: 
      context: ./Front
      dockerfile: front_V2.Dockerfile
    networks:
      - library-network
    env_file:
      - ./Front/.env
  back:
    build: ./Back
    networks:
      - library-network
    environment:
      - NODE_ENV=production
#   front:
#     image: nginx:1.27-alpine3.20
#     ports:
#       - "80:80"
#     volumes: 
#       - ./Front/build:/usr/share/nginx/html
#     networks:
#       - library-network
networks:
  library-network:
  