services:
  front:
    build: ./Front
    ports:
      - "80:3000"
    networks:
      - library-network
  back:
    build: ./Back
    ports:
      - "81:5000"
    networks:
      - library-network
networks:
  library-network: 
